//
// Created by adrian on 12/10/19.
//

#ifndef PROYECTO2_DATOS2_ALGORITMOSGENETICOS_H
#define PROYECTO2_DATOS2_ALGORITMOSGENETICOS_H


class AlgoritmosGeneticos {

};


#endif //PROYECTO2_DATOS2_ALGORITMOSGENETICOS_H
